development:
  adapter: postgresql
  encoding: unicode
  database: sample_app_development
  host: localhost
  pool: 5
  username: sample_app
  password: VZz4AP6Q

test:
  adapter: postgresql
  encoding: unicode
  database: sample_app_test
  host: localhost
  pool: 5
  username: sample_app
  password: VZz4AP6Q


