common: &db
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: sample_app
  password: VZz4AP6Q

development:
  <<: *db
  database: sample_app_development

test:
  <<: *db
  database: sample_app_test
